- name: Install OS dependencies
  hosts: all
  tasks:
    - name: Install build essentials
      become: true
      ansible.builtin.package:
        name: build-essential
        state: present

- name: Set up Rust toolchain
  hosts: all
  tasks:
    - name: Check whether rustup is available
      ansible.builtin.stat:
        path: "{{ rustup_bin }}"
      register: rustup_lookup_result

    - block:
        - name: Download Rust installer
          ansible.builtin.get_url:
            url: https://sh.rustup.rs
            dest: /tmp/rust_installer.sh
            mode: u=rwx,g=,o=
            force: true

        - name: Run Rust installer
          ansible.builtin.command: /tmp/rust_installer.sh -y

        - name: Validate that rustup is available
          ansible.builtin.stat:
            path: "{{ rustup_bin }}"
          register: rustup_lookup_again_result
          failed_when: not rustup_lookup_again_result.stat.exists

      when: not rustup_lookup_result.stat.exists

    - name: Update Rust toolchain
      ansible.builtin.command: "{{ rustup_bin }} update"

    - name: Validate that cargo is available
      ansible.builtin.stat:
        path: "{{ cargo_bin }}"
      register: cargo_lookup_result
      failed_when: not cargo_lookup_result.stat.exists

- name: Configure udev
  hosts: all
  tasks:
    - name: Install joystick rules
      become: true
      ansible.builtin.copy:
        src: files/99-joystick-links.rules
        dest: /etc/udev/rules.d/99-joystick-links.rules
        owner: root
        group: root
        mode: u=rw,g=r,o=r

- name: Install roestbak service
  hosts: all
  vars:
    - project_root_local: "{{ playbook_dir }}/../"
    - project_root_remote: "{{ ansible_env.HOME }}/src/roestbak"
  tasks:
    - name: Create sources directory
      ansible.builtin.file:
        path: "{{ project_root_remote }}"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Synchronize sources
      ansible.posix.synchronize:
        src: '"{{ project_root_local }}/{{ item }}"'
        dest: "{{ project_root_remote }}/"
        archive: true
        perms: false
        owner: false
        group: false
        delete: true
      loop:
        - Cargo.toml
        - Cargo.lock
        - src

    - name: Build service
      ansible.builtin.command: "{{ cargo_bin }} build --release"
      args:
        chdir: "{{ project_root_remote }}"

    - name: Create bin directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/bin"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Copy service to bin directory
      ansible.builtin.copy:
        src: "{{ project_root_remote }}/target/release/roestbak"
        dest: "{{ ansible_env.HOME }}/bin"
        remote_src: true
        mode: preserve
      notify: 
        - Restart service

    - name: Install service unit file
      become: true
      ansible.builtin.template:
        src: files/roestbak.service.j2
        dest: /etc/systemd/system/roestbak.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: 
        - Restart service

    - name: Disable service
      become: true
      ansible.builtin.systemd:
        name: roestbak.service
        enabled: false

    - name: Enable service
      become: true
      ansible.builtin.systemd:
        name: roestbak.service
        enabled: true

  post_tasks:
    - name: Ensure service is started
      become: true
      ansible.builtin.systemd:
        name: roestbak.service
        state: started

  handlers:
    - name: Restart service
      become: true
      ansible.builtin.systemd:
        name: roestbak.service
        state: restarted
